# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-10 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenEds',
            fields=[
                ('crn', models.IntegerField(db_column='CRN', primary_key=True, serialize=False)),
                ('subject', models.CharField(db_column='Subject', max_length=255)),
                ('number', models.IntegerField(db_column='Number')),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('credithours', models.CharField(db_column='CreditHours', max_length=255)),
                ('degreeattributes', models.CharField(blank=True, db_column='DegreeAttributes', max_length=255, null=True)),
                ('scheduleinfo', models.CharField(blank=True, db_column='ScheduleInfo', max_length=255, null=True)),
                ('section', models.CharField(blank=True, db_column='Section', max_length=255, null=True)),
                ('enrollmentstatus', models.CharField(blank=True, db_column='EnrollmentStatus', max_length=255, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=255, null=True)),
                ('starttime', models.CharField(blank=True, db_column='StartTime', max_length=255, null=True)),
                ('endtime', models.CharField(blank=True, db_column='EndTime', max_length=255, null=True)),
                ('days', models.CharField(blank=True, db_column='Days', max_length=255, null=True)),
                ('room', models.CharField(blank=True, db_column='Room', max_length=255, null=True)),
                ('building', models.CharField(blank=True, db_column='Building', max_length=255, null=True)),
                ('instructors', models.CharField(blank=True, db_column='Instructors', max_length=255, null=True)),
            ],
            options={
                'db_table': 'gen_eds',
            },
        ),
        migrations.CreateModel(
            name='Gpa',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('year', models.IntegerField(db_column='Year')),
                ('term', models.CharField(db_column='Term', max_length=255)),
                ('subject', models.CharField(db_column='Subject', max_length=255)),
                ('number', models.IntegerField(db_column='Number')),
                ('coursetitle', models.CharField(db_column='CourseTitle', max_length=255)),
                ('avggpa', models.FloatField(blank=True, db_column='avgGpa', null=True)),
                ('a', models.IntegerField(blank=True, db_column='A', null=True)),
                ('b', models.IntegerField(blank=True, db_column='B', null=True)),
                ('c', models.IntegerField(blank=True, db_column='C', null=True)),
                ('d', models.IntegerField(blank=True, db_column='D', null=True)),
                ('f', models.IntegerField(blank=True, db_column='F', null=True)),
                ('total', models.IntegerField(blank=True, db_column='Total', null=True)),
                ('primaryinstructor', models.CharField(blank=True, db_column='PrimaryInstructor', max_length=255, null=True)),
            ],
            options={
                'db_table': 'gpa',
            },
        ),
        migrations.CreateModel(
            name='RegularCourses',
            fields=[
                ('crn', models.IntegerField(db_column='CRN', primary_key=True, serialize=False)),
                ('subject', models.CharField(db_column='Subject', max_length=255)),
                ('number', models.IntegerField(db_column='Number')),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('credithours', models.CharField(db_column='CreditHours', max_length=255)),
                ('scheduleinfo', models.CharField(blank=True, db_column='ScheduleInfo', max_length=255, null=True)),
                ('section', models.CharField(blank=True, db_column='Section', max_length=255, null=True)),
                ('enrollmentstatus', models.CharField(blank=True, db_column='EnrollmentStatus', max_length=255, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=255, null=True)),
                ('starttime', models.CharField(blank=True, db_column='StartTime', max_length=255, null=True)),
                ('endtime', models.CharField(blank=True, db_column='EndTime', max_length=255, null=True)),
                ('days', models.CharField(blank=True, db_column='Days', max_length=255, null=True)),
                ('room', models.CharField(blank=True, db_column='Room', max_length=255, null=True)),
                ('building', models.CharField(blank=True, db_column='Building', max_length=255, null=True)),
                ('instructors', models.CharField(blank=True, db_column='Instructors', max_length=255, null=True)),
            ],
            options={
                'db_table': 'regular_courses',
            },
        ),
    ]
