# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-10 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiuc_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('professor_name', models.CharField(max_length=255)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='GenEds',
            new_name='GenEd',
        ),
        migrations.RenameModel(
            old_name='RegularCourses',
            new_name='RegularCourse',
        ),
    ]
