# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-10 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uiuc_scheduler', '0002_auto_20200410_1701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rating',
        ),
    ]
