# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-10 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiuc_scheduler', '0003_auto_20200410_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='subject',
            field=models.CharField(default='CS', max_length=255),
            preserve_default=False,
        ),
    ]
