# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-10 22:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uiuc_scheduler', '0004_rating_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
