# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-30 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uiuc_scheduler', '0005_rating_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gened',
            name='building',
        ),
        migrations.RemoveField(
            model_name='gened',
            name='credithours',
        ),
        migrations.RemoveField(
            model_name='gened',
            name='days',
        ),
        migrations.RemoveField(
            model_name='gened',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='gened',
            name='enrollmentstatus',
        ),
        migrations.RemoveField(
            model_name='gened',
            name='instructors',
        ),
        migrations.RemoveField(
            model_name='gened',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gened',
            name='number',
        ),
        migrations.RemoveField(
            model_name='gened',
            name='room',
        ),
        migrations.RemoveField(
            model_name='gened',
            name='scheduleinfo',
        ),
        migrations.RemoveField(
            model_name='gened',
            name='section',
        ),
        migrations.RemoveField(
            model_name='gened',
            name='starttime',
        ),
        migrations.RemoveField(
            model_name='gened',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='gened',
            name='type',
        ),
    ]
