# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-30 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiuc_scheduler', '0006_auto_20200430_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularcourse',
            name='term',
            field=models.CharField(db_column='Term', default='fa', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regularcourse',
            name='year',
            field=models.IntegerField(db_column='Year', default=2020),
            preserve_default=False,
        ),
    ]
