# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-30 03:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uiuc_scheduler', '0007_auto_20200430_0242'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rating',
            table='ratings',
        ),
    ]
