# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-26 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uiuc_scheduler', '0010_auto_20200626_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='friendRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_id', to=settings.AUTH_USER_MODEL)),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friend_requests',
            },
        ),
    ]
