# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-26 20:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uiuc_scheduler', '0011_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='receiver_id',
            field=models.ForeignKey(db_column='receiver_id', on_delete=django.db.models.deletion.CASCADE, related_name='receiver_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='request_id',
            field=models.AutoField(db_column='request_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='sender_id',
            field=models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendships',
            name='friend_one_id',
            field=models.ForeignKey(db_column='friend_one_id', on_delete=django.db.models.deletion.CASCADE, related_name='friend_one_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendships',
            name='friend_two_id',
            field=models.ForeignKey(db_column='friend_two_id', on_delete=django.db.models.deletion.CASCADE, related_name='friend_two_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendships',
            name='friendship_id',
            field=models.AutoField(db_column='friendship_id', primary_key=True, serialize=False),
        ),
    ]
