# Generated by Django 3.1.3 on 2021-01-05 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uiuc_scheduler', '0012_auto_20200626_2032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegularCourse',
        ),
    ]
