# Generated by Django 3.1.3 on 2021-01-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiuc_scheduler', '0013_delete_regularcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularCourse',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('crn', models.IntegerField(db_column='CRN')),
                ('year', models.IntegerField(db_column='Year')),
                ('term', models.CharField(db_column='Term', max_length=255)),
                ('subject', models.CharField(db_column='Subject', max_length=255)),
                ('number', models.IntegerField(db_column='Number')),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('credithours', models.CharField(db_column='CreditHours', max_length=255)),
                ('scheduleinfo', models.CharField(blank=True, db_column='ScheduleInfo', max_length=255, null=True)),
                ('section', models.CharField(blank=True, db_column='Section', max_length=255, null=True)),
                ('enrollmentstatus', models.CharField(blank=True, db_column='EnrollmentStatus', max_length=255, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=255, null=True)),
                ('starttime', models.CharField(blank=True, db_column='StartTime', max_length=255, null=True)),
                ('endtime', models.CharField(blank=True, db_column='EndTime', max_length=255, null=True)),
                ('days', models.CharField(blank=True, db_column='Days', max_length=255, null=True)),
                ('room', models.CharField(blank=True, db_column='Room', max_length=255, null=True)),
                ('building', models.CharField(blank=True, db_column='Building', max_length=255, null=True)),
                ('instructors', models.CharField(blank=True, db_column='Instructors', max_length=255, null=True)),
            ],
            options={
                'db_table': 'regular_courses',
                'unique_together': {('crn', 'type')},
            },
        ),
    ]
