# Generated by Django 3.1.3 on 2021-01-20 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uiuc_scheduler', '0014_regularcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('schedule_id', models.IntegerField(db_column='schedule_id')),
                ('crn', models.IntegerField(db_column='crn')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='following',
            fields=[
                ('follow_id', models.AutoField(db_column='follow_id', primary_key=True, serialize=False)),
                ('follower_id', models.ForeignKey(db_column='follower_id', on_delete=django.db.models.deletion.CASCADE, related_name='follower_id', to=settings.AUTH_USER_MODEL)),
                ('following_id', models.ForeignKey(db_column='following_id', on_delete=django.db.models.deletion.CASCADE, related_name='following_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'following',
            },
        ),
    ]
