# Generated by Django 3.1.3 on 2021-01-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiuc_scheduler', '0015_following_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='term',
            field=models.CharField(default='Fall 2020', max_length=255),
            preserve_default=False,
        ),
    ]
