# Generated by Django 3.1.3 on 2021-01-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiuc_scheduler', '0016_schedule_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='year',
            field=models.IntegerField(db_column='year', default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='term',
            field=models.CharField(db_column='term', max_length=255),
        ),
    ]
